//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.TreatmentsHistory = new HashSet<TreatmentsHistory>();
        }
    
        public System.Guid Id { get; set; }
        public string Name_surname { get; set; }
        public string Id_number { get; set; }
        public string Company { get; set; }
        public Nullable<System.Guid> Room_number { get; set; }
        public int Is_here { get; set; }
        public int Vegetarian { get; set; }
        public int Questionnaire { get; set; }
        public int Invoice { get; set; }
    
        public virtual ICollection<TreatmentsHistory> TreatmentsHistory { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
