//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public System.Guid Id { get; set; }
        public int Number { get; set; }
        public int How_many_persons { get; set; }
        public double Size { get; set; }
        public double Price { get; set; }
        public int Available { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
    }
}
