//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatments
    {
        public Treatments()
        {
            this.TreatmentsHistory = new HashSet<TreatmentsHistory>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int Duration { get; set; }
        public string Description { get; set; }
        public int Active { get; set; }
    
        public virtual ICollection<TreatmentsHistory> TreatmentsHistory { get; set; }
    }
}
